# Generated by Django 4.2.2 on 2023-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark',
            field=models.BooleanField(default=True, verbose_name='is_dark_theme'),
        ),
    ]
